login = "{user_id}이(가) 로그인하였습니다."
login_not_exist = "존재하지 않은 아이디({user_id})로 로그인 시도하였습니다."
login_pwd_fail = "패스워드가 일치하지 않아 로그인에 실패하였습니다."
logout = "{user_id}이(가) 로그아웃하였습니다."
create_user = "새로운 사용자({user_id}를 생성하였습니다."
update_user = "사용자({user_id} 정보가 갱신되었습니다."
delete_user = "사용자({user_id}를 삭제하였습니다."
